# Generated by Django 4.2 on 2023-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="choices",
        ),
        migrations.AddField(
            model_name="poll",
            name="choice1",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="poll",
            name="choice2",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="poll",
            name="choice3",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="poll",
            name="choice4",
            field=models.CharField(default="", max_length=100),
        ),
    ]
