# Generated by Django 4.2 on 2023-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_remove_poll_choices_poll_choice1_poll_choice2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="choice1",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="poll",
            name="choice2",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="poll",
            name="choice3",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="poll",
            name="choice4",
            field=models.CharField(max_length=100),
        ),
    ]
