# Generated by Django 4.2 on 2023-07-07 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_choice_question_delete_poll_choice_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="group_member",
        ),
    ]
