# Generated by Django 4.2.3 on 2023-07-24 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userPortrait', '0001_initial'),
        ('specialist', '0001_initial'),
        ('services', '0002_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPortrait.userprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialist.specialist')),
            ],
        ),
    ]
