# Generated by Django 4.2.2 on 2023-07-07 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_room', '0001_initial'),
        ('room_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='room_message_images')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_member.roommember')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_room.group_room')),
            ],
        ),
    ]
