# Generated by Django 4.2.2 on 2023-07-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('groupmember', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupmember.groupmember')),
            ],
        ),
    ]
