# Generated by Django 4.2.2 on 2023-07-01 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('userPortrait', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userPortrait.userprofile')),
            ],
        ),
    ]
