# Generated by Django 4.2.2 on 2023-07-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupmember', '0001_initial'),
        ('group_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_room.group_room')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupmember.groupmember')),
            ],
        ),
    ]
